export enum contractsTypes {
    FETCH_CONTRACTS_REQUEST = "FETCH_CONTRACTS_REQUEST",
    FETCH_CONTRACTS_SUCCESS = "FETCH_CONTRACTS_SUCCESS",
    FETCH_CONTRACTS_FAILURE = "FETCH_CONTRACTS_FAILURE"
  }
  